/*
 * Standard types and types of escapes
 */
keywords{
  isKeyword:[symbol]{}.
  isKeyword('|').
  isKeyword('||').
  isKeyword(';').
  isKeyword(':').
  isKeyword('::').
  isKeyword(',').
  isKeyword('..').
  isKeyword('.').
  isKeyword(',..').
  isKeyword('?').
  isKeyword('!').
  isKeyword('^').
  isKeyword('~').
  isKeyword('/~').
  isKeyword('/-').
  isKeyword('`').
  isKeyword('=').
  isKeyword('==').
  isKeyword('.=').
  isKeyword(':=').
  isKeyword('%=').
  isKeyword('=>').
  isKeyword('->').
  isKeyword(':-').
  isKeyword(':--').
  isKeyword('-->').
  isKeyword('::=').
  isKeyword('<~').
  isKeyword('<=').
  isKeyword('$').
  isKeyword('*').
  isKeyword('+').
  isKeyword('/').
  isKeyword('-').
  isKeyword('-+').
  isKeyword('*>').
  isKeyword('{}').
  isKeyword('[]').
  isKeyword('\\+').
  isKeyword('\\=').
  isKeyword('!=').
  isKeyword('.').
  isKeyword('%').
  isKeyword('%%').
  isKeyword('@').
  isKeyword('in').
  isKeyword('valof').
  isKeyword('valis').
  isKeyword('action').
  isKeyword('false').
  isKeyword('true').
  isKeyword('fail').
  isKeyword('spawn').
  isKeyword('using').
  isKeyword('onerror').
  isKeyword('raise').
  isKeyword('timeout').
  isKeyword('sync').
  isKeyword('import').
  isKeyword('number').
  isKeyword('integer').
  isKeyword('float').
  isKeyword('symbol').
  isKeyword('char').
  isKeyword('string').
  isKeyword('logical').
  isKeyword('opaque').
  isKeyword('top').
  isKeyword('this').
  isKeyword('case').
  isKeyword('#').
}